export default {
    'SET_SAVE_FILE_DIR': 'SET_SAVE_FILE_DIR', // 设置存储文件的地址
    'SET_CREATE_NEW_DIR_STATE': 'SET_CREATE_NEW_DIR_STATE',
    'SET_COMPRESS_MODE': 'SET_COMPRESS_MODE',
    'SET_COMPRESS_LEVEL': 'SET_COMPRESS_LEVEL'
}